const res = [
  {
    URL: "https://myturbo.appdeft.biz/api/program/course/79/Activities",
    METHOD: "GET",
    PAYLOAD: {},
    RESPONSE: [
      {
        id: 171,
        title: "Read Chapter 1, 2, & 3 in Bowersox (2019)",
        type: "Reading",
        resource: [
          {
            course: 79,
            id: 100,
            name: "Bowersox (2019)",
            type: "Textbook",
            interaction_time: null,
            url: "",
            citation:
              "Bowersox, D. (2019). Supply Chain Logistics Management (5th Edition). McGraw-Hill Higher Education (US).  https://bookshelf.vitalsource.com/books/9780077729134",
          },
        ],
        course: 79,
        assessment: null,
        interaction_time: 4,
        clock_hour: false,
        activity_details: "",
      },
      {
        id: 175,
        title: "Class Meeting",
        type: "Project",
        resource: [],
        course: 79,
        assessment: null,
        interaction_time: 4,
        clock_hour: true,
        activity_details: "",
      },
      {
        id: 173,
        title: "Read Chapter 4 and 5 in Bowersox",
        type: "Reading",
        resource: [
          {
            course: 79,
            id: 100,
            name: "Bowersox (2019)",
            type: "Textbook",
            interaction_time: null,
            url: "",
            citation:
              "Bowersox, D. (2019). Supply Chain Logistics Management (5th Edition). McGraw-Hill Higher Education (US).  https://bookshelf.vitalsource.com/books/9780077729134",
          },
        ],
        course: 79,
        assessment: null,
        interaction_time: 3,
        clock_hour: false,
        activity_details: "",
      },
      {
        id: 186,
        title: "A generic journal reading.",
        type: "Reading",
        resource: [],
        course: 79,
        assessment: null,
        interaction_time: 3,
        clock_hour: false,
        activity_details: "",
      },
      {
        id: 172,
        title: "Online Class Meeting",
        type: "Project",
        resource: [],
        course: 79,
        assessment: null,
        interaction_time: 4,
        clock_hour: true,
        activity_details: "",
      },
      {
        id: 176,
        title: "Read Chapter 6 & 7 in Bowersox",
        type: "Reading",
        resource: [
          {
            course: 79,
            id: 100,
            name: "Bowersox (2019)",
            type: "Textbook",
            interaction_time: null,
            url: "",
            citation:
              "Bowersox, D. (2019). Supply Chain Logistics Management (5th Edition). McGraw-Hill Higher Education (US).  https://bookshelf.vitalsource.com/books/9780077729134",
          },
        ],
        course: 79,
        assessment: null,
        interaction_time: 3,
        clock_hour: false,
        activity_details: "",
      },
      {
        id: 174,
        title: "Class Meeting",
        type: "Online Class Meeting",
        resource: [],
        course: 79,
        assessment: null,
        interaction_time: 3,
        clock_hour: true,
        activity_details: "",
      },
    ],
  },
  {
    URL: "https://myturbo.appdeft.biz/api/program/course/87/Activities",
    METHOD: "POST",
    PAYLOAD: {
      title: "prep1",
      type: "Reading",
      resource: [172],
      activity_details: "pres1 det",
      interaction_time: "5",
      clock_hour: true,
    },
    RESPONSE: [
      {
        id: 195,
        title: "prep1",
        type: "Reading",
        resource: [
          {
            course: 87,
            id: 172,
            name: "collegebook",
            type: "Textbook",
            interaction_time: null,
            url: "",
            citation: "fgh g dfg dfg",
          },
        ],
        course: 87,
        assessment: null,
        interaction_time: 5,
        clock_hour: true,
        activity_details: "pres1 det",
      },
      {
        status: 201,
      },
    ],
  },
  {
    URL: "https://myturbo.appdeft.biz/api/program/course/79/Activities/:id",
    METHOD: "GET",
    RESPONSE: {
      id: 196,
      title: "pre and 1",
      type: "Watch Movie",
      resource: [
        {
          course: 87,
          id: 172,
          name: "collegebook",
          type: "Textbook",
          interaction_time: null,
          url: "",
          citation: "fgh g dfg dfg",
        },
      ],
      course: 87,
      assessment: null,
      interaction_time: 5.5,
      clock_hour: true,
      activity_details: "dfgdfg",
      module_assigned: [210],
    },
  },
  {
    URL: "https://myturbo.appdeft.biz/api/program/course/79/Activities/:id",
    METHOD: "PUT",
    PAYLOAD: {
      title: "pre and 1123",
      type: "Watch Movie",
      resource: [172],
      activity_details: "dfgdfg",
      interaction_time: 5.5,
      clock_hour: true,
    },
    RESPONSE: {
      id: 196,
      title: "pre and 1",
      type: "Watch Movie",
      resource: [
        {
          course: 87,
          id: 172,
          name: "collegebook",
          type: "Textbook",
          interaction_time: null,
          url: "",
          citation: "fgh g dfg dfg",
        },
      ],
      course: 87,
      assessment: null,
      interaction_time: 5.5,
      clock_hour: true,
      activity_details: "dfgdfg",
      module_assigned: [210],
    },
  },
];
